# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-11 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='source',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='media',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
