# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-11 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20170411_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
