# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-09 12:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20170405_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 9, 12, 55, 3, 810056, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
